#+TITLE: cl-xrandr-dmenu
#+AUTHOR: Lou Woell
#+MAIL: lou.woell@posteo.de

A dmenu interface for xrandr written in Common Lisp.

The dmenu interface is heavily inspired by [[https://github.com/luksamuk/powerlisp][Powerlisp]].

This script is intended to replace some bash scripts for my screen setup. Right
now it is able to turn xrandr outputs on and off, manipulate their relative
position, rotate them and change which one is primary.

There's also a function that automatically fixes the screen set up in case a
screen was disconnected before the output was disabled. No guarantee that there
aren't edge cases where the way this is implemented produces unwanted results.

* Dependencies

- dmenu
- sbcl
- quicklisp
- libnotify (calls ~notify-send~ through ~uiop:run-program~)

* Installation

Compile using the makefile provided.

#+begin_src bash
  git clone  https://github.com/einsiedlerspiel/cl-xrandr-dmenu.git cl-xrandr-dmenu
  cd cl-xrandr-dmenu
  make
#+end_src

Optionally you can also execute ~make install~ which will copy the binary to ~~/.local/bin~.

* Usage

#+begin_src
xrandr-dmenu [OPTIONS]

Options:
  -h, --help            Display help and exit
  -f, --no-output-fix   By default xrandr dmenu checks if `xrandr
                        --list-monitors' lists more monitors than `xrandr' lists
                        active outputs and disables any surplus monitors. This
                        option turns that behavior off.

WM Options:
  These options handle things specifc to the windowmanager in use.

  -i, --restart-i3      if this option is spepcified i3 will be restarted after
                        every xrandr action. Probably causes problems if i3 is
                        not installed or running.
#+end_src
